clevis: add missing dependencies
clevis depends on polkit (by the means of udisks2). Add the missing dependency
so that we can pass cve-check on world without having an error like:

  ERROR: Nothing PROVIDES 'udisks2' (but [...]/meta-ledge-secure/meta-ledge-secure/recipes-security/clevis/clevis_git.bb DEPENDS on or otherwise requires )
  udisks2 was skipped: missing required distro feature 'polkit' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'clevis', 'udisks2`

Signed-off-by: Marta Rybczynska <marta.rybczynska@huawei.com>
Signed-off-by: Marta Rybczynska <marta.rybczynska@linaro.org>