packaggroup-ledge-tsn: remove the recipe for now
With cve-check on world, build fails with missing dependencies with:

ERROR: Nothing RPROVIDES 'open62541-examples' (but /meta-ledge-secure/meta-ledge-secure/recipes-samples/packagegroups/packagegroup-ledge-tsn.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'open62541-examples' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['open62541-examples']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-ledge-tsn', 'open62541-examples']

Remove the recipe until the issue is fixed. The recipe isn't referenced
anywhere in this layer.

Signed-off-by: Marta Rybczynska <marta.rybczynska@huawei.com>
Signed-off-by: Marta Rybczynska <marta.rybczynska@linaro.org>